using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using System.Text;
using System.Threading.Tasks;

namespace CardsAgainstHumanity
{
    internal class Deck
    {
        private List<ICard> _blackDeck;
        private List<ICard> _whiteDeck;

        public List<ICard> blackDeck { get { return _blackDeck; } }
        public List<ICard> whiteDeck { get { return _whiteDeck; } }

        public Deck()
        {
            _blackDeck = new List<ICard>()
            {
                new BlackCard (true, 1, "Hey Reddit! I’m __________. Ask me anything."),
                new BlackCard (true, 1, "Introducing X-treme Baseball! It’s like baseball, but with __________!"),
                new BlackCard (true, 1, "What is Batman’s guilty pleasure?"),
                new BlackCard (true, 1, "TSA guidelines now prohibit __________ on airplanes."),
                new BlackCard (true, 1, "Next from J.K. Rowling: Harry Potter and the Chamber of __________."),
                new BlackCard (true, 2, "That’s right, I killed __________. How, you ask? __________."),
                new BlackCard (true, 1, "I’m sorry, Professor, but I couldn’t complete my homework because of __________."),
                new BlackCard (true, 2, "And the Academy Award for __________ goes to __________."),
                new BlackCard (true, 1, "Dude, do not go in that bathroom. There’s __________ in there."),
                new BlackCard (true, 1, "How did I lose my virginity?"),
                new BlackCard (true, 1, "It’s a pity that kids these days are all getting involved with __________."),
                new BlackCard (true, 2, "Step 1: __________. Step 2: __________. Step 3: Profit."),
                new BlackCard (true, 1, "__________. Betcha can’t have just one!"),
                new BlackCard (true, 1, "Kids, I don’t need drugs to get high. I’m high on __________."),
                new BlackCard (true, 2, "For my next trick, I will pull __________  out of __________."),
                new BlackCard (true, 1, "Mitch McConnell can’t cum without __________."),
                new BlackCard (true, 1, "In the new Disney Channel Original Movie, Hannah Montana struggles with __________ for the first time."),
                new BlackCard (true, 1, "What’s my secret power?"),
                new BlackCard (true, 1, "I’m going ona cleanse this week. Nothing but kale juice and __________."),
                new BlackCard (true, 3, "__________ + __________ = __________."),
                new BlackCard (true, 1, "When Pharaoh remained unmoved, Moses called down a Plague of __________."),
                new BlackCard (true, 1, "Just once, I’d like to hear you say \"Thanks, Mom. Thanks for __________.\""),
                new BlackCard (true, 1, "Daddy, why is mommy crying?"),
                new BlackCard (true, 2, "When I was tripping on acid, __________ turned into __________."),
                new BlackCard (true, 1, "50% of all marriages end in __________."),
                new BlackCard (true, 1, "My fellow Americans: Before this decade is out, we will have __________ on the moon!"),
                new BlackCard (true, 1, "This season at Steppenwolf, Samuel Beckett’s classic existential play: Waiting for __________."),
                new BlackCard (true, 1, "Instead of coal, Santa now gives the bad children __________."),
                new BlackCard (true, 1, "Life for American Indians was forever changed when the White Man introduced them to __________."),
                new BlackCard (true, 1, "What’s Teach For America using to inspire inner city students to succeed?"),
                new BlackCard (true, 1, "Maybe she’s born with it. Maybe it’s __________."),
                new BlackCard (true, 1, "My name is Peter Parker. I was bitten by a radioactive spider, and now I’m __________."),
                new BlackCard (true, 1, "White people like __________."),
                new BlackCard (true, 2, "__________ is a slippery slope that leads to __________."),
                new BlackCard (true, 1, "Why do I hurt all over?"),
                new BlackCard (true, 1, "A romantic, candlelit dinner would be incomplete without __________."),
                new BlackCard (true, 1, "Just saw this upsetting video! Please retweet!! #stop__________."),
                new BlackCard (true, 1, "Fun tip! When your man asks you to go down on him, try surprising him with __________ instead."),
                new BlackCard (true, 1, "The class field trip was completely ruined by __________."),
                new BlackCard (true, 1, "What’s a girl’s best friend?"),
                new BlackCard (true, 1, "Dear Abby, I’m having some trouble with __________ and would like your advice."),
                new BlackCard (true, 2, "In Jordan Peele’s new thriller, a young family discovers that __________ had really been __________ all along."),
                new BlackCard (true, 1, "When I am President, I will create the Department of __________."),
                new BlackCard (true, 1, "What are my parents hiding from me?"),
                new BlackCard (true, 1, "What never fails to liven up the party?"),
                new BlackCard (true, 1, "IF you like  __________. YOU MIGHT BE A REDNECK."),
                new BlackCard (true, 1, "Make a haiku. "),
                new BlackCard (true, 1, "What made my first kiss so awkward?"),
                new BlackCard (true, 1, "Hey guys, welcome to Chili’s! Would you like to start the night off right with __________?"),
                new BlackCard (true, 1, "I got 99 problems but __________ ain't one."),
                new BlackCard (true, 1, "__________. It’s a trap!"),
                new BlackCard (true, 1, "Hulu’s new reality show features twelve hot singles living with __________."),
                new BlackCard (true, 1, "What would grandma find disturbing, yet oddly charming?"),
                new BlackCard (true, 1, "__________. That was so metal."),
                new BlackCard (true, 2, "I never truly understood __________ until I encountered __________."),
                new BlackCard (true, 1, "During sex, I like to think about __________."),
                new BlackCard (true, 1, "What ended my last relationship?"),
                new BlackCard (true, 1, "What’s that sound?"),
                new BlackCard (true, 1, "Uh, hey guys, I know this was my idea, but I’m having serious doubts about __________."),
                new BlackCard (true, 1, "Why am I sticky?"),
                new BlackCard (true, 1, "I’m no doctor, but I’m pretty sure what you’re suffering from is called \"__________\"."),
                new BlackCard (true, 1, "What’s there a ton of in heaven?"),
                new BlackCard (true, 1, "After four platinum albums and three Grammys, it’s time to get back to my roots, to what inspired me to make music in the first place: __________."),
                new BlackCard (true, 1, "What will always get you laid?"),
                new BlackCard (true, 2, "They said we were crazy. They said we couldn’t put __________ inside of __________. They were wrong."),
                new BlackCard (true, 2, "Lifetime® presents \"__________: the Story of __________.\""),
                new BlackCard (true, 1, "__________: kid-tested, mother-approved."),
                new BlackCard (true, 1, "Why can’t I sleep at night?"),
                new BlackCard (true, 1, "What’s that smell?"),
                new BlackCard (true, 1, "Why is Brett so sweaty?"),
                new BlackCard (true, 1, "This is the way the world ends. This is the way the world ends. Not with a bang but with __________."),
                new BlackCard (true, 1, "Coming to Broadway this season, __________: The Musical."),
                new BlackCard (true, 1, "Here is the church. Here is the steeple. Open the doors. And there is __________."),
                new BlackCard (true, 1, "But before I kill you, Mr. Bond, I must show you __________."),
                new BlackCard (true, 1, "A recent laboratory study shows that undergraduates have 50% less sex after being exposed to __________."),
                new BlackCard (true, 2, "Introducing the amazing superhero/sidekick duo! It’s __________ and __________!"),
                new BlackCard (true, 1, "Next on ESPN2: The World Series of __________."),
                new BlackCard (true, 1, "When I am a billionaire, I shall erect a 50-foot statue to commemorate __________."),
                new BlackCard (true, 1, "Military historians remember Alexander the Great for his brilliant use of __________ against the Persians."),
                new BlackCard (true, 1, "War! What is it good for?"),
                new BlackCard (true, 1, "What gives me uncontrollable gas?"),
                new BlackCard (true, 1, "The new Chevy Tahoe. With the power and space to take __________ everywhere you go."),
                new BlackCard (true, 1, "Well if you’ll excuse me, gentlemen, I have a date with __________."),
                new BlackCard (true, 1, "Alternative medicine is now embracing the curative powers of __________."),
                new BlackCard (true, 1, "As the mom of five rambunctious boys, I’m no stranger to __________."),
                new BlackCard (true, 1, "__________. High five, bro."),
                new BlackCard (true, 1, "Today on Maury: \"Help! My son is __________!\""),
                new BlackCard (true, 1, "I get by with a little help from __________."),
                new BlackCard (true, 1, "1/5 Stars. Do NOT go here! Found in my fettuccine alfredo!"),
                new BlackCard (true, 1, "I drink to forget __________."),
                new BlackCard (true, 1, "I’m LeBron James, and when I’m not slamming dunks, I love __________."),
                new BlackCard (true, 1, "What makes life worth living?"),
                new BlackCard (true, 1, "Arby’s: We Have __________."),
                new BlackCard (true, 1, "Mr. and Mrs. Diaz, we called you in because we’re concerned about Cynthia. Are you aware that your daughter is __________?"),
                new BlackCard (true, 1, "If you can’t be with the one you love, love __________."),
                new BlackCard (true, 1, "Brought to you by Bud Light®, the Official Beer of __________."),
                new BlackCard (true, 1, "Click Here for __________!!!"),
                new BlackCard (true, 1, "Check me out, yo! I call this dance move \"__________.\""),
                new BlackCard (true, 1, "Old MacDonald had __________. E-I-E-1-O."),
                new BlackCard (true, 1, "Men’s Wearhouse: You’re gonna like __________. I guarantee it."),
            };

            _whiteDeck = new List<ICard>() 
            {
                new WhiteCard (true, "Silence."),
                new WhiteCard (true, "The illusion of choice in a late-stage capitalist society."),
                new WhiteCard (true, "Many bats."),
                new WhiteCard (true, "Hot Asian men."),
                new WhiteCard (true, "Shame."),
                new WhiteCard (true, "Website."),
                new WhiteCard (true, "Assaulting a police officer."),
                new WhiteCard (true, "Magnets."),
                new WhiteCard (true, "A sorry excuse for a father."),
                new WhiteCard (true, "Seeing what happens when you lock people in a room with hungry seagulls."),
                new WhiteCard (true, "A crucifixion."),
                new WhiteCard (true, "A narc."),
                new WhiteCard (true, "Boneless buffalo wings."),
                new WhiteCard (true, "A live studio audience."),
                new WhiteCard (true, "Complaining."),
                new WhiteCard (true, "Authentic Mexican cuisine."),
                new WhiteCard (true, "Doing crimes."),
                new WhiteCard (true, "COVID-19."),
                new WhiteCard (true, "Crippling debt."),
                new WhiteCard (true, "Daddy issues."),
                new WhiteCard (true, "Working in an Amazon warehouse."),
                new WhiteCard (true, "A fart so powerful that it wakes the giants from their thousand-year slumber."),
                new WhiteCard (true, "Former President George W. Bush."),
                new WhiteCard (true, "Full frontal nudity."),
                new WhiteCard (true, "Covering myself with Parmesan cheese and chili flakes because I am pizza."),
                new WhiteCard (true, "Laying an egg."),
                new WhiteCard (true, "Getting naked and watching Nickelodeon."),
                new WhiteCard (true, "Pretending to care."),
                new WhiteCard (true, "Having big dreams but no realistic way to achieve them."),
                new WhiteCard (true, "Seeing Grandma naked."),
                new WhiteCard (true, "Boogers."),
                new WhiteCard (true, "The Confederate flag."),
                new WhiteCard (true, "The miracle of childbirth."),
                new WhiteCard (true, "A positive attitude!"),
                new WhiteCard (true, "Having a stroke."),
                new WhiteCard (true, "White privilege."),
                new WhiteCard (true, "Emerging from the sea and rampaging through Tokyo."),
                new WhiteCard (true, "The Hamburglar."),
                new WhiteCard (true, "The tampon from my vagina."),
                new WhiteCard (true, "The Blood of Christ."),
                new WhiteCard (true, "Soft, kissy missionary sex."),
                new WhiteCard (true, "BATMAN!"),
                new WhiteCard (true, "Agriculture."),
                new WhiteCard (true, "Barely making $25,000 a year."),
                new WhiteCard (true, "Natural selection."),
                new WhiteCard (true, "Boomers."),
                new WhiteCard (true, "Dropping a hot doodie out of my turd hole."),
                new WhiteCard (true, "My abusive boyfriend who really isn’t so bad once you get to know him."),
                new WhiteCard (true, "Prescription pain killers."),
                new WhiteCard (true, "Swooping."),
                new WhiteCard (true, "Mansplaining."),
                new WhiteCard (true, "A homoerotic volleyball montage."),
                new WhiteCard (true, "Alexandria Ocasio-Cortez."),
                new WhiteCard (true, "Putting things where they go."),
                new WhiteCard (true, "Holding a pepper grinder for some reason."),
                new WhiteCard (true, "Giving birth in prison."),
                new WhiteCard (true, "An old guy who’s almost dead."),
                new WhiteCard (true, "Kanye West."),
                new WhiteCard (true, "Hot cheese."),
                new WhiteCard (true, "Getting serial killed."),
                new WhiteCard (true, "Seven dead and three in critical condition."),
                new WhiteCard (true, "Smegma."),
                new WhiteCard (true, "Alcoholism."),
                new WhiteCard (true, "A middle-aged man on roller skates."),
                new WhiteCard (true, "Nobody giving a shit about anything anymore."),
                new WhiteCard (true, "Grabbing my man by his love handles and fucking his big ass."),
                new WhiteCard (true, "Stuffing my peehole with Tic Tacs."),
                new WhiteCard (true, "Self-loathing."),
                new WhiteCard (true, "Sitting on my face and telling me I’m garbage."),
                new WhiteCard (true, "Half-assed foreplay."),
                new WhiteCard (true, "The Holy Bible."),
                new WhiteCard (true, "German dungeon porn."),
                new WhiteCard (true, "Being on fire."),
                new WhiteCard (true, "Using comedy as a coping mechanism."),
                new WhiteCard (true, "Ghandi."),
                new WhiteCard (true, "Your weird brother."),
                new WhiteCard (true, "Birth control."),
                new WhiteCard (true, "Nasty shit, like real sick stuff."),
                new WhiteCard (true, "An erection that lasts longer than four hours."),
                new WhiteCard (true, "A three-way with my wife and Shaquille O’Neal."),
                new WhiteCard (true, "The past."),
                new WhiteCard (true, "My genitals."),
                new WhiteCard (true, "An endless stream of diarrhea."),
                new WhiteCard (true, "Science."),
                new WhiteCard (true, "Not reciprocating oral sex."),
                new WhiteCard (true, "Flightless birds."),
                new WhiteCard (true, "A good sniff."),
                new WhiteCard (true, "50,000 volts straight to the nipples."),
                new WhiteCard (true, "Da clurb."),
                new WhiteCard (true, "Dead birds everywhere."),
                new WhiteCard (true, "The arrival of the pizza."),
                new WhiteCard (true, "Permanent Orgasm-Face Disorder."),
                new WhiteCard (true, "The cool, refreshing taste of Pepsi.®"),
                new WhiteCard (true, "Irritable bowel syndrome."),
                new WhiteCard (true, "Oprah."),
                new WhiteCard (true, "Wondering if it’s possible to get some of that salsa to go."),
                new WhiteCard (true, "Bananas."),
                new WhiteCard (true, "Cringe."),
                new WhiteCard (true, "Me jubbly bubblies."),
                new WhiteCard (true, "Switching to Geico.®"),
                new WhiteCard (true, "Peeing a little bit."),
                new WhiteCard (true, "Wet dreams."),
                new WhiteCard (true, "The Jews."),
                new WhiteCard (true, "My cheating son-of-a-bitch husband."),
                new WhiteCard (true, "Powerful thighs."),
                new WhiteCard (true, "These hoes."),
                new WhiteCard (true, "The only gay person in a hundred miles."),
                new WhiteCard (true, "Having sex for the first time."),
                new WhiteCard (true, "Donald J. Trump."),
                new WhiteCard (true, "Kissing grandma on the forehead and turning off her life support."),
                new WhiteCard (true, "A certain je ne sais quoi."),
                new WhiteCard (true, "An AR-15 assault rifle."),
                new WhiteCard (true, "My good bra."),
                new WhiteCard (true, "Punching a congressman in the face."),
                new WhiteCard (true, "Saying everything is okay when everything is clearly not okay."),
                new WhiteCard (true, "Being rich."),
                new WhiteCard (true, "Floating down the Hudson River with the other garbage."),
                new WhiteCard (true, "Republicans."),
                new WhiteCard (true, "Sniffing and kissing my feet."),
                new WhiteCard (true, "A much younger woman."),
                new WhiteCard (true, "Poverty."),
                new WhiteCard (true, "Kamala Harris."),
                new WhiteCard (true, "Committing suicide."),
                new WhiteCard (true, "A loser like you."),
                new WhiteCard (true, "A mistake."),
                new WhiteCard (true, "Squirting."),
                new WhiteCard (true, "Wizard music."),
                new WhiteCard (true, "The Kool-Aid Man."),
                new WhiteCard (true, "Explaining the difference between sex and gender."),
                new WhiteCard (true, "Free samples."),
                new WhiteCard (true, "Hurting those closest to me."),
                new WhiteCard (true, "Feeding strawberries to my manslut."),
                new WhiteCard (true, "The Three-Fifths Compromise."),
                new WhiteCard (true, "Lactation."),
                new WhiteCard (true, "Laughing over champagne flutes while the poor freeze to death outside."),
                new WhiteCard (true, "Shutting up so I can watch the game."),
                new WhiteCard (true, "Eating a hard boiled egg out of my husband’s asshole."),
                new WhiteCard (true, "Doing white people shit with a bunch of white people."),
                new WhiteCard (true, "One titty hanging out."),
                new WhiteCard (true, "Fucking all my dad’s friends."),
                new WhiteCard (true, "Drinking gasoline to see what it tastes like."),
                new WhiteCard (true, "Inappropriate yodeling."),
                new WhiteCard (true, "Puberty."),
                new WhiteCard (true, "Ghosts."),
                new WhiteCard (true, "50 mg of Zoloft daily."),
                new WhiteCard (true, "Fucking my sister."),
                new WhiteCard (true, "Braiding three penises into a Twizzler."),
                new WhiteCard (true, "Vigorous jazz hands."),
                new WhiteCard (true, "Getting fingered."),
                new WhiteCard (true, "My Uber driver, Pavel."),
                new WhiteCard (true, "GoGurt.®"),
                new WhiteCard (true, "Police brutality."),
                new WhiteCard (true, "An abortion."),
                new WhiteCard (true, "Preteens."),
                new WhiteCard (true, "My fat daughter."),
                new WhiteCard (true, "Clean drinking water."),
                new WhiteCard (true, "Fading away into nothingness."),
                new WhiteCard (true, "Darth Vader."),
                new WhiteCard (true, "A sad handjob."),
                new WhiteCard (true, "Exactly what you’d expect."),
                new WhiteCard (true, "Critical race theory."),
                new WhiteCard (true, "Adderall.®"),
                new WhiteCard (true, "Your mom."),
                new WhiteCard (true, "Sideboob."),
                new WhiteCard (true, "An octopus giving seven handjobs and smoking a cigarette."),
                new WhiteCard (true, "My neck, my back, my pussy, and my crack."),
                new WhiteCard (true, "J.D. Power and his associates."),
                new WhiteCard (true, "Mouth herpes."),
                new WhiteCard (true, "Sperm whales."),
                new WhiteCard (true, "Women of color."),
                new WhiteCard (true, "Men discussing their feelings in an emotionally healthy way."),
                new WhiteCard (true, "Incest."),
                new WhiteCard (true, "Pac-Man uncontrollably guzzling cum."),
                new WhiteCard (true, "Casually suggesting a threesome."),
                new WhiteCard (true, "Running out of semen."),
                new WhiteCard (true, "God."),
                new WhiteCard (true, "Backing over a kid with the Buick."),
                new WhiteCard (true, "Pissing in my thirsty mouth."),
                new WhiteCard (true, "Emotions."),
                new WhiteCard (true, "Licking things to claim them as your own."),
                new WhiteCard (true, "Jobs."),
                new WhiteCard (true, "The placenta."),
                new WhiteCard (true, "Lips that could suck the chrome off a doorknob."),
                new WhiteCard (true, "The Bachelorette season finale."),
                new WhiteCard (true, "Throwing grapes at aman until he loses touch with reality."),
                new WhiteCard (true, "Establishing dominance."),
                new WhiteCard (true, "Finger painting."),
                new WhiteCard (true, "Old-people smell."),
                new WhiteCard (true, "Getting crushed by a vending machine."),
                new WhiteCard (true, "My inner demons."),
                new WhiteCard (true, "A Super Soaker™ full of cat pee."),
                new WhiteCard (true, "Aunt Jemima’s® racist pancake sauce."),
                new WhiteCard (true, "Cuddling."),
                new WhiteCard (true, "However much weed $20 can buy."),
                new WhiteCard (true, "Battlefield amputations."),
                new WhiteCard (true, "Spaghetti? Again?"),
                new WhiteCard (true, "Ronald Reagan."),
                new WhiteCard (true, "A disappointing birthday party."),
                new WhiteCard (true, "Nachos for the table."),
                new WhiteCard (true, "Becoming a blueberry."),
                new WhiteCard (true, "A tiny horse."),
                new WhiteCard (true, "Crab."),
                new WhiteCard (true, "Selling crack to children."),
                new WhiteCard (true, "The Wendy’s Spicy Chicken Sandwich."),
                new WhiteCard (true, "Brown people."),
                new WhiteCard (true, "Sexually active band geeks."),
                new WhiteCard (true, "Pedophiles."),
                new WhiteCard (true, "Yeast."),
                new WhiteCard (true, "How bad my daughter fucked up her dance recital."),
                new WhiteCard (true, "Rectangles."),
                new WhiteCard (true, "Being fucking pathetic."),
                new WhiteCard (true, "Poor people."),
                new WhiteCard (true, "Only dating Asian women."),
                new WhiteCard (true, "Putting children in cages."),
                new WhiteCard (true, "Karen. "),
                new WhiteCard (true, "How amazing it is to be on mushrooms."),
                new WhiteCard (true, "Judging everyone."),
                new WhiteCard (true, "An all-white jury."),
                new WhiteCard (true, "Getting married, having a few kids, buying some stuff, retiring to Florida, and dying."),
                new WhiteCard (true, "Some god damn peace and quiet."),
                new WhiteCard (true, "AIDS."),
                new WhiteCard (true, "Pictures of boobs."),
                new WhiteCard (true, "Strong female characters."),
                new WhiteCard (true, "Getting decapitated by a helicopter."),
                new WhiteCard (true, "Hospice care."),
                new WhiteCard (true, "Getting really high."),
                new WhiteCard (true, "The opioid epidemic."),
                new WhiteCard (true, "Penis envy."),
                new WhiteCard (true, "Gay conversion therapy."),
                new WhiteCard (true, "Burgers and pussy."),
                new WhiteCard (true, "Smelling of cum."),
                new WhiteCard (true, "The KKK."),
                new WhiteCard (true, "A pangender octopus who roams the cosmos in search of love."),
                new WhiteCard (true, "Meth."),
                new WhiteCard (true, "Cyanide."),
                new WhiteCard (true, "Holding down a child and farting all over him."),
                new WhiteCard (true, "A Bop It.™"),
                new WhiteCard (true, "A whole thing of butter."),
                new WhiteCard (true, "Still being a virgin."),
                new WhiteCard (true, "Solving problems with violence."),
                new WhiteCard (true, "Getting cummed on."),
                new WhiteCard (true, "Pixelated bukkake."),
                new WhiteCard (true, "A lifetime of sadness."),
                new WhiteCard (true, "A non-disclosure agreement."),
                new WhiteCard (true, "Dick pics."),
                new WhiteCard (true, "Racism."),
                new WhiteCard (true, "Menstrual rage."),
                new WhiteCard (true, "Sunshine and rainbows."),
                new WhiteCard (true, "Joe Biden."),
                new WhiteCard (true, "Three ounces of clean urine."),
                new WhiteCard (true, "Doing drugs with my kids."),
                new WhiteCard (true, "My gay best friend."),
                new WhiteCard (true, "A gossamer stream of jizz that catches the light as it arcs through the morning air."),
                new WhiteCard (true, "Executing a hostage every hour."),
                new WhiteCard (true, "The rhythms of Africa."),
                new WhiteCard (true, "Breaking out into song and dance."),
                new WhiteCard (true, "Leprosy."),
                new WhiteCard (true, "Gloryholes."),
                new WhiteCard (true, "Nipple blades."),
                new WhiteCard (true, "The heart of a child."),
                new WhiteCard (true, "Puppies!"),
                new WhiteCard (true, "Fellowship in Christ."),
                new WhiteCard (true, "My wife having sex with your wife."),
                new WhiteCard (true, "Waking up half-naked in a Denny’s parking lot."),
                new WhiteCard (true, "An older woman who knows her way around the penis."),
                new WhiteCard (true, "Getting drugs off the street and into my body."),
                new WhiteCard (true, "Daniel Radcliffe’s delicious asshole."),
                new WhiteCard (true, "Active listening."),
                new WhiteCard (true, "Ethnic cleansing."),
                new WhiteCard (true, "Itchy pussy."),
                new WhiteCard (true, "Blowing my boyfriend so hard he shits."),
                new WhiteCard (true, "A fuck-ton of almonds."),
                new WhiteCard (true, "A cis man playing a trans woman."),
                new WhiteCard (true, "Waiting till marriage."),
                new WhiteCard (true, "NFTs."),
                new WhiteCard (true, "Pretending to be a dentist."),
                new WhiteCard (true, "The Devil himself."),
                new WhiteCard (true, "Salvation."),
                new WhiteCard (true, "Erectile dysfunction."),
                new WhiteCard (true, "My collection of Japanese sex toys."),
                new WhiteCard (true, "The Pope."),
                new WhiteCard (true, "White people."),
                new WhiteCard (true, "Tentacle porn."),
                new WhiteCard (true, "My bright pink fuckhole."),
                new WhiteCard (true, "How far I can get my own penis up my butt."),
                new WhiteCard (true, "Having anuses for eyes."),
                new WhiteCard (true, "Two Xanax and a bottle of wine."),
                new WhiteCard (true, "My pet scorpion, Tina."),
                new WhiteCard (true, "Danny DeVito."),
                new WhiteCard (true, "The magic of live theatre."),
                new WhiteCard (true, "Throwing a virgin into a volcano."),
                new WhiteCard (true, "Dwayne “The Rock” Johnson."),
                new WhiteCard (true, "Accepting the way things are."),
                new WhiteCard (true, "NBA superstar LeBron James."),
                new WhiteCard (true, "Listening to her problems without trying to solve them."),
                new WhiteCard (true, "Therapy."),
                new WhiteCard (true, "Being fat and stupid."),
                new WhiteCard (true, "Pooping back and forth. Forever."),
                new WhiteCard (true, "Tearing that ass up like wrapping paper on Christmas morning."),
                new WhiteCard (true, "More elephant cock than I bargained for."),
                new WhiteCard (true, "A salty surprise."),
                new WhiteCard (true, "The South."),
                new WhiteCard (true, "The violation of our most basic human rights."),
                new WhiteCard (true, "Saudi oil money."),
                new WhiteCard (true, "Consensual sex."),
                new WhiteCard (true, "Telling a shitty story that goes nowhere."),
                new WhiteCard (true, "A good, strong gorilla."),
                new WhiteCard (true, "Seeing my father cry."),
                new WhiteCard (true, "Necrophilia."),
                new WhiteCard (true, "Being a woman."),
                new WhiteCard (true, "Getting into a pretty bad car accident."),
                new WhiteCard (true, "Bill Nye the Science Guy."),
                new WhiteCard (true, "Black people."),
                new WhiteCard (true, "Prostate stimulation."),
                new WhiteCard (true, "Lunchables.”"),
                new WhiteCard (true, "Bitches."),
                new WhiteCard (true, "Some punk kid who stole my turkey sandwich."),
                new WhiteCard (true, "Heartwarming orphans."),
                new WhiteCard (true, "Spirit Airlines. "),
                new WhiteCard (true, "Bubble butt bottom boys."),
                new WhiteCard (true, "A bowl of mayonnaise and human teeth."),
                new WhiteCard (true, "Fiery poops."),
                new WhiteCard (true, "Saying “I love you.”"),
                new WhiteCard (true, "Inserting a Mason jar into my anus."),
                new WhiteCard (true, "The true meaning of Christmas."),
                new WhiteCard (true, "Whatever’s in the fridge."),
                new WhiteCard (true, "Owning and operating a Chili’s franchise."),
                new WhiteCard (true, "Estrogen."),
                new WhiteCard (true, "Girls."),
                new WhiteCard (true, "The Russians."),
                new WhiteCard (true, "A bleached asshole."),
                new WhiteCard (true, "Fucking the weatherman on live television."),
                new WhiteCard (true, "PTSD."),
                new WhiteCard (true, "Dark and mysterious forces beyond our control."),
                new WhiteCard (true, "Smallpox blankets."),
                new WhiteCard (true, "Masturbating."),
                new WhiteCard (true, "Hobos."),
                new WhiteCard (true, "Queefing."),
                new WhiteCard (true, "My fuckslave, Reginald."),
                new WhiteCard (true, "Cardi B."),
                new WhiteCard (true, "Viagra.®"),
                new WhiteCard (true, "Soup that is too hot."),
                new WhiteCard (true, "The ugliest boy in town."),
                new WhiteCard (true, "Explaining how vaginas work."),
                new WhiteCard (true, "Academy Award winner Meryl Streep."),
                new WhiteCard (true, "Drinking alone."),
                new WhiteCard (true, "Dick fingers."),
                new WhiteCard (true, "Multiple stab wounds."),
                new WhiteCard (true, "The death penalty."),
                new WhiteCard (true, "A supportive touch on the lower back."),
                new WhiteCard (true, "Anal beads."),
                new WhiteCard (true, "Slaughtering innocent civilians."),
                new WhiteCard (true, "Pulling out."),
                new WhiteCard (true, "Being able to talk to elephants."),
                new WhiteCard (true, "Horse meat."),
                new WhiteCard (true, "A really cool hat."),
                new WhiteCard (true, "Stalin."),
                new WhiteCard (true, "A stray pube."),
                new WhiteCard (true, "Worshipping that pussy."),
                new WhiteCard (true, "Completely unwarranted confidence."),
                new WhiteCard (true, "Doin’ it in the butt."),
                new WhiteCard (true, "My ex-wife."),
                new WhiteCard (true, "Tiny tits that say “Yippee!” when you touch them."),
                new WhiteCard (true, "Touching a pug right on his penis."),
                new WhiteCard (true, "A windmill full of corpses."),
                new WhiteCard (true, "The whole enchilada."),
                new WhiteCard (true, "Vladimir Putin."),
                new WhiteCard (true, "The Patriarchy."),
                new WhiteCard (true, "The glass ceiling."),
                new WhiteCard (true, "White Card Vomiting seafood and bleeding anally."),
                new WhiteCard (true, "The American Dream."),
                new WhiteCard (true, "Not wearing pants."),
                new WhiteCard (true, "My balls on your face."),
                new WhiteCard (true, "Pooping in a laptop and closing it."),
                new WhiteCard (true, "Some bitch who loves pineapple."),
                new WhiteCard (true, "Foreskin."),
                new WhiteCard (true, "Getting crushed between Serena Williams’ thighs."),
                new WhiteCard (true, "Italians."),
                new WhiteCard (true, "A fetus."),
                new WhiteCard (true, "Firing a rifle into the air while balls deep ina squealing hog."),
                new WhiteCard (true, "Natural gas."),
                new WhiteCard (true, "Over 10,000 Guatemalan migrants."),
                new WhiteCard (true, "Toxic masculinity."),
                new WhiteCard (true, "My relationship status."),
                new WhiteCard (true, "An unwanted pregnancy."),
                new WhiteCard (true, "marvel"),
                new WhiteCard (true, "My boss."),
                new WhiteCard (true, "Bees?"),
                new WhiteCard (true, "Harry Potter erotica."),
                new WhiteCard (true, "Giving birth to the Antichrist."),
                new WhiteCard (true, "Three dicks at the same time."),
                new WhiteCard (true, "Nazis."),
                new WhiteCard (true, "8 oz. of Mexican black-tar heroin."),
                new WhiteCard (true, "What that mouth do."),
                new WhiteCard (true, "Dead parents."),
                new WhiteCard (true, "Object permanence."),
                new WhiteCard (true, "Opposable thumbs."),
                new WhiteCard (true, "Racially-biased SAT questions."),
                new WhiteCard (true, "The Great Depression."),
                new WhiteCard (true, "Chainsaws for hands."),
                new WhiteCard (true, "Nicolas Cage."),
                new WhiteCard (true, "Like, whatever."),
                new WhiteCard (true, "Explosions."),
                new WhiteCard (true, "Not vaccinating my children because I am stupid."),
                new WhiteCard (true, "Our dildo."),
                new WhiteCard (true, "Huffing spray paint."),
                new WhiteCard (true, "Aman on the brink of orgasm."),
                new WhiteCard (true, "Using a condom."),
                new WhiteCard (true, "Invading Poland."),
                new WhiteCard (true, "My vagina."),
                new WhiteCard (true, "Assless chaps."),
                new WhiteCard (true, "Murder."),
                new WhiteCard (true, "Sipping kombucha like a smug piece of shit."),
                new WhiteCard (true, "Her Majesty, Queen Elizabeth Il."),
                new WhiteCard (true, "Black Jesus."),
                new WhiteCard (true, "Memes."),
                new WhiteCard (true, "Sex with animals."),
                new WhiteCard (true, "Being marginalized."),
                new WhiteCard (true, "Goblins."),
                new WhiteCard (true, "Hope."),
                new WhiteCard (true, "Liberals."),
                new WhiteCard (true, "A micropenis."),
                new WhiteCard (true, "Committing treason."),
                new WhiteCard (true, "A ball of earwax, semen, and toenail clippings."),
                new WhiteCard (true, "A horde of Vikings."),
                new WhiteCard (true, "Hot people."),
                new WhiteCard (true, "Seething with quiet resentment."),
                new WhiteCard (true, "An Oedipus complex."),
                new WhiteCard (true, "Geese."),
                new WhiteCard (true, "Extremely tight pants."),
                new WhiteCard (true, "Fox News."),
                new WhiteCard (true, "A little boy who won’t shut the fuck up about dinosaurs."),
                new WhiteCard (true, "Bryan Cranston, of all people."),
                new WhiteCard (true, "Vehicular manslaughter."),
                new WhiteCard (true, "Women’s suffrage."),
                new WhiteCard (true, "Some guy."),
                new WhiteCard (true, "Judge Judy."),
                new WhiteCard (true, "Climbing a telephone pole and becoming one with the T-Mobile network."),
                new WhiteCard (true, "This month’s mass shooting."),
                new WhiteCard (true, "Barack Obama."),
                new WhiteCard (true, "Illegal immigrants."),
                new WhiteCard (true, "My horny, horny son."),
                new WhiteCard (true, "The female orgasm."),
                new WhiteCard (true, "Heteronormativity."),
                new WhiteCard (true, "Crumbs all over the god damn carpet."),
                new WhiteCard (true, "Corporate America."),
                new WhiteCard (true, "The wifi password."),
                new WhiteCard (true, "A time-traveling Chinese general from the Shang Dynasty."),
                new WhiteCard (true, "A bird that shits human turds."),
                new WhiteCard (true, "A mopey zoo lion."),
                new WhiteCard (true, "Pro-life protesters."),
                new WhiteCard (true, "Poor life choices."),
                new WhiteCard (true, "My sex life."),
                new WhiteCard (true, "Auschwitz."),
                new WhiteCard (true, "Cocaine for lunch."),
                new WhiteCard (true, "All the dudes I’ve fucked."),
                new WhiteCard (true, "The clitoris."),
                new WhiteCard (true, "The Big Bang."),
                new WhiteCard (true, "Land mines."),
                new WhiteCard (true, "The entire Mormon Tabernacle Choir."),
                new WhiteCard (true, "A micropig wearing a tiny raincoat and booties."),
                new WhiteCard (true, "Penis breath."),
                new WhiteCard (true, "A gambling problem."),
                new WhiteCard (true, "Man meat."),
                new WhiteCard (true, "Me time."),
                new WhiteCard (true, "The Underground Railroad."),
                new WhiteCard (true, "Kayaking with my sluts."),
                new WhiteCard (true, "Boppin’ my flopper."),
                new WhiteCard (true, "Lumberjack fantasies."),
                new WhiteCard (true, "Goat."),
                new WhiteCard (true, "Women in yogurt commercials."),
                new WhiteCard (true, "Literally begging to die."),
                new WhiteCard (true, "Being a motherfucking sorcerer."),
                new WhiteCard (true, "My Black ass."),
                new WhiteCard (true, "Genuine human connection."),
                new WhiteCard (true, "Announcing that I am about to cum."),
                new WhiteCard (true, "Balls."),
                new WhiteCard (true, "Grandma."),
                new WhiteCard (true, "Friction."),
                new WhiteCard (true, "Applying topical ointment to my grandfather’s infected penis."),
                new WhiteCard (true, "Farting and walking away."),
                new WhiteCard (true, "Being a dick to children."),
                new WhiteCard (true, "One trillion dollars."),
                new WhiteCard (true, "Drowning the kids in the bathtub."),
                new WhiteCard (true, "Dying."),
                new WhiteCard (true, "Drinking out of the toilet and eating garbage."),
                new WhiteCard (true, "The gays."),
                new WhiteCard (true, "The screams... the terrible screams."),
                new WhiteCard (true, "Men."),
                new WhiteCard (true, "The bombing of Nagasaki."),
                new WhiteCard (true, "Fake tits."),
                new WhiteCard (true, "The Amish."),
                new WhiteCard (true, "Calling the cops on an innocent Black man."),
                new WhiteCard (true, "My ugly face and bad personality."),
                new WhiteCard (true, "A bitch slap."),
                new WhiteCard (true, "A brain tumor."),
                new WhiteCard (true, "Giggling like an anime girl."),
                new WhiteCard (true, "Swamp ass."),
                new WhiteCard (true, "The milkman."),
                new WhiteCard (true, "Cards Against Humanity."),
            };
        }
    }
}
